### ISSUE TITLE
My output video only 1KB

### ISSUE THREAD

**Issue by mingjieshen** [modelsbymike3d/SnapCameraPyBot#1]
Why is my output video only 1KB（No error reported）

**Comment by modelsbymike3d** [comment]
Can you provide more information such as your operating system and Python version? Can you see your video going into Snap Camera? Can you provide any screenshots?

**Comment by mingjieshen** [comment]
Thank you for your prompt reply.
My operating system is win11x64.
Python 3.7.3 and 3.9.1 all have been tried
Here is my screenshot:
![image](https://user-images.githubusercontent.com/41664285/150634970-f6376d50-8b27-4c7d-84e5-9e7683f412ab.png)
![image](https://user-images.githubusercontent.com/41664285/150634986-b6fd9488-de89-4dfe-a345-b6fa31763c2c.png)
![image](https://user-images.githubusercontent.com/41664285/150635000-c202aa1b-d2f6-47b1-95d3-30f6721a971a.png)
I suspect that the pictures of each frame have not been saved

**Comment by jeanshirt** [comment]
I have the same problem, 1kb output video, my system version is Win11

**Comment by modelsbymike3d** [comment]
Curious that you are each on Windows 11. That ffmpeg message does look suspicious. I’ll check which version of opencv I have installed; I didn’t specify versions in requirements.txt so it could be something to do with that.

**Comment by mingjieshen** [comment]
My opencv version is 4.5.5

**Comment by modelsbymike3d** [comment]
Here are the versions I have on my machine:
* `pyvirtualcam` 0.8.0
* `opencv-python` 4.5.4.58

Does this happen with all input videos you try?

**Comment by jeanshirt** [comment]
The size of videowriter is inconsistent with the frame. In this case, the saved video will be very small, less than 1KB. The solution is to adjust the size to be consistent.

**Comment by gaurav-95** [comment]
- Operating system: Windows 10
- Python version: 3.8
- pyvirtualcam version: 0.9.1
- Virtual camera (OBS, v4l2loopback, UnityCapture):  OBS
- Virtual camera version: 27.2.4

**Describe the bug**
...

There is no error message produced when running the code. The output file is always a 1 kb file with no video.
Not sure whats causing this.

**Replicate the Problem**

The only change I made to the original code was
this line (MP4V to mp4v) changed to lowercase (line 38) of main.py

```py
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
```
...

**Output**
```py
(tenv) PS C:\Users\Admin\Desktop\Projects\Virtual_tryon\SnapCameraPyBot-main> & c:/Users/Admin/Desktop/Projects/Virtual_tryon/tenv/Scripts/python.exe c:/Users/Admin/Desktop/Projects/Virtual_tryon/SnapCameraPyBot-main/main.py -f rishi-sunak-small.mp4
Input video parameters:
        fps: 25.0
        width: 1280
        height: 720
        frames: 102
Configuring virtual camera
Using virtual camera: OBS Virtual Camera
100%|███████████████████████████████████████████████████████████████████████████| 102/102 [00:27<00:00,  3.68it/s]
```

**Debugging Tried**

Used different camera index, did not work,

ISSUE IS RESOLVED

UPDATE: This works 100%. Its exactly as @jeanshirt mentions the size of the video was not being fed in properly
Set the height and width of the output file to that of the capture device

**Comment by mrjonnybgood** [comment]
Hi there Mike. Just hitting a wall with your suggestion regarding size of video not being fed in properly and setting the height and width og the output file to that of the capture device. I have configured everything correctly in all 3 softwares (snap camera, OBS and Splitcam) but still getting 1K file result. I'm not really a coder so I wondered if I was supposed to adjust anything in the python script? Sorry for being a bit slow but do you mean adjusting the script somehow, or just making sure the 3 softwares are on the same dimension settings. 
Many thanks, Jonathan (and thank you for the great idea)

**Comment by SunShark7** [comment]
Hello Mike, thanks for your good work. I got some problem when running the code and getting the frame by frame video. Just like others, after done the process, the video result 1 KB. I've adjusted the video size, even get the python version as you did. But it didn't work. 
Here is some information.

**- opencv-python 4.5.4.58
- pyvirtualcam 0.9.0**
![Snipaste_2022-11-08_20-38-39](https://user-images.githubusercontent.com/74172465/200580728-e3adc32c-d814-45d2-890b-36befd1c9039.png)


**-snapCam, splitCam and video are all set to 1280*720 30fps**

![Snipaste_2022-11-08_20-37-44](https://user-images.githubusercontent.com/74172465/200581526-d811e697-39e6-4702-beff-9759cea4c689.png)
![Snipaste_2022-11-08_20-37-16](https://user-images.githubusercontent.com/74172465/200581591-87f4a464-8c0a-4334-a3da-94ad3fdab585.png)
![Snipaste_2022-11-08_20-36-37](https://user-images.githubusercontent.com/74172465/200581607-a3efed85-a93d-4f10-837a-e4a42ecdbf51.png)

**- 2 running erros**
1 can't grab frame. Error: -1072875772
2 [ WARN:0] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (1022) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638

![Snipaste_2022-11-08_20-47-00](https://user-images.githubusercontent.com/74172465/200582374-927f1bea-fecb-47e4-8f84-44a68549b084.png)

PS: I'm not sure if it's still video size problem, but the video size looks to fit the cameras setting. If you could upload the video(rickroll.mp4) you had tested on here, maybe we could figure it out that weather is our video problem. Anyway, look forward to hear from you.

**Comment by SunShark7** [comment]
**output result**
![Snipaste_2022-11-08_22-06-18](https://user-images.githubusercontent.com/74172465/200586175-8f61aea0-fb6e-4fca-919f-dabf62727e08.png)
![Snipaste_2022-11-08_22-07-55](https://user-images.githubusercontent.com/74172465/200586206-927cc8e0-9bef-436d-a203-21749457de2f.png)

**Comment by modelsbymike3d** [comment]
Hey everyone, I finally got the Windows 11 update, but that alone doesn't seem to cause any issues - the script still ran for me.

Here is the [rickroll video](https://drive.google.com/file/d/1oir_R27uPnjWgrN-dp1fFW3HUVQkZ4MG/view?usp=share_link) I use to test. Give that a try to see if it is your video or something else.

Here are all my installed dependencies with version numbers (some of them might not be relevant):
```txt
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
ca-certificates=2021.10.8=h5b45459_0
colorama=0.4.4=pypi_0
imageio=2.10.3=pypi_0
numpy=1.21.4=pypi_0
opencv-python=4.5.4.58=pypi_0
openssl=1.1.1l=h8ffe710_0
pillow=8.4.0=pypi_0
pip=21.3.1=pyhd8ed1ab_0
python=3.7.10=h6244533_0
python_abi=3.7=2_cp37m
pyvirtualcam=0.8.0=pypi_0
pyyaml=6.0=pypi_0
setuptools=58.5.3=py37h03978a9_0
sqlite=3.36.0=h8ffe710_2
tqdm=4.62.3=pypi_0
ucrt=10.0.20348.0=h57928b3_0
vc=14.2=hb210afc_5
vs2015_runtime=14.29.30037=h902a5da_5
wheel=0.37.0=pyhd8ed1ab_1
```

I haven't tried with other Python/package versions, so I'm not sure if that is causing problems.

With regards to configuring video resolution, the script sets its output resolution automatically, so you just need to make sure SplitCam/Snap Camera match.

If you've been having issues, give that rickroll.mp4 video a try. If that still doesn't work, I'll try to dig into this a bit more, but this project is my first time working with pyvirtualcam and opencv so I can't promise anything.

**Comment by SunShark7** [comment]
Thanks the video!

**Comment by SunShark7** [comment]
It doesn't work with the rickroll video either after running the code with it on my computer. So I think it's not the video problem. I looked through the code in main.py file  and tried to understand them. Then I  printed the parameters from the captured video which I believe that would be the output video we want. Here is what I found, the captured video resolutions didn't match the input one, so it would definitely result wrong video (opencv thing),eg 1kb video. 
![Snipaste_2022-11-11_10-32-56](https://user-images.githubusercontent.com/74172465/201258116-02cb11e4-4a38-4ac9-9b64-10f4d01886b1.png)
![Snipaste_2022-11-11_10-38-29](https://user-images.githubusercontent.com/74172465/201258257-d34a43b9-d155-416a-b922-2ff87cf598f6.png)
![Snipaste_2022-11-11_10-39-38](https://user-images.githubusercontent.com/74172465/201258293-ed8b752d-51b7-4593-90f4-fe2b95e4ee74.png)

I'm not so sure why the video resolutions didn't match, even though I've set them right on splitCam and snap camera. Should I also set OBS ?? Anyway, I think it might be depend on the internet speed. Even I've set snap camera to 1920*1080 resolution, it's still result  640*480. The capture video's resolutions are variable. So what I did is to adjust the output video's resolutions basing on capture one instead of input one. And it works.

![Snipaste_2022-11-11_10-42-22](https://user-images.githubusercontent.com/74172465/201262457-9ba9d3b4-326f-4d23-abb6-5f638d463c2b.png)
![Snipaste_2022-11-11_10-45-38](https://user-images.githubusercontent.com/74172465/201262542-6f9a0c44-5a2a-4857-b452-efcd320c4866.png)
![Snipaste_2022-11-11_10-46-34](https://user-images.githubusercontent.com/74172465/201262552-f7ca9b15-8fa1-4682-bca3-64ec293d7e7c.png)

**Comment by SunShark7** [comment]
There is another problem I found after successfully processing the code and getting the video. The video I got doesn't have the filter lens on from snap camera. It's almost the same to the input video except for its size. I feel like I'm being rickrolled... Anyway I've added some codes to track what video I got during  proccessing the code. As I said it's the same as the input video. I'm still confused why this could happen. I only have one webcam (snap camera), and it capture the camera right and there is also a filter len on in snap cam. Snap cam don't allow people to capture it? But why it exposes well in OBS? Maybe I think too much.
![Snipaste_2022-11-11_11-00-36](https://user-images.githubusercontent.com/74172465/201265443-d5727350-cce1-4df0-ab9e-c429e98316f2.png)
![Snipaste_2022-11-11_11-10-35](https://user-images.githubusercontent.com/74172465/201265454-d97b443f-3604-4a58-9be5-356b8e1f9d9d.png)

PS：This is my first time to meet python, maybe I'm wrong in explaining the code.

**Comment by SunShark7** [comment]
Problem solved! I've moved the snapCam file to other disk, its cam can't be traced, so I got the wrong video. Now I've deleted it and install snapcam again, it works.

**Comment by 2022is** [comment]
> Problem solved! I've moved the snapCam file to other disk, its cam can't be traced, so I got the wrong video. Now I've deleted it and install snapcam again, it works.

hi SunShark7,can you share me your whole file&folder ? i had modify the main.py code same as your picture but still get 1kb file (PS:my snapcam still work fine because i get backup method from someone , the snapcam still can apply filter while code is running , but the result is 1kb)

**Comment by NoUserNameForYou** [comment]
Mike, can you share your environment please? Just 7zip it and upload it. Many of the versions you listed can't be downloaded. I also get 1kb file.
